# Generic MoveIt Travis Continuous Integration Configuration File
# Works with all MoveIt! repositories/branches
# Author: Dave Coleman, Jonathan Bohren
sudo: required
dist: trusty
services:
  - docker
language:
  - cpp
  - python
compiler:
  - gcc
notifications:
  email:
    recipients:
      - dave.hershberger@sri.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  matrix:
    - ROS_DISTRO=crystal TEST=clang-format
    - ROS_DISTRO=crystal ROS_REPO=ros

before_script:
  - git clone --branch ros2 -q https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - source .moveit_ci/travis.sh
